name: CI
on: push

jobs:
  test:
    name: Pytest Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
      - name: debug
        run: |
          conda env update --name base --file environment.yml
          pip install -e .
          conda env list
      - name: Testing with pytest
        run: pytest