name: CI
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  test:
    name: Pytest Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
      - name: Env info
        run: conda --version
        run: which python
        run: ls
      - name: Creating conda Env
        # creating conda virtual env using YAML file
        run: conda env create -f environment.yml
        # activating the newly created env
        run: conda activate feat
        # installing feat package in editable mode
        run: pip install -e .
      - name: Testing with pytest
        run: pytest
