name: CI
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  test:
    name: Pytest Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
      - name: Creating conda environment   
        run: |
          conda env create -f environment.yml
      - name: debug
        run: |
          conda env list
          conda activate feat
          conda list
      # conda activate feat
      # pip install -e .
      # - name: Testing with pytest
      #   run: pytest
